# ex01 · 张量操作（对应教材 2.1 数据操作）

> **做题流程**：每道题先在【预测区】写下你的答案（形状/数值/报错），再运行代码验证。
> **做完再看** `solutions/ex01-答案.md`。
>
> 难度标记：🌱 基础（预测+验证）｜🔧 变式（改动观察）｜🚀 挑战（闭卷复现）

In [8]:
import torch

## 题 1 🌱 预测 `arange` + `reshape` 的输出

下面这行代码会输出什么？写出完整 tensor。

**【你的预测】**
tensor([[0, 1, 2],
        [3, 4, 5]])

In [6]:
torch.arange(6).reshape(2, 3)

tensor([[0, 1, 2],
        [3, 4, 5]])

## 题 2 🌱 用三种不同 API 创建全 1 张量

目标形状 `(3, 2)`。你能想到哪三种？提示：`torch.ones`、`torch.full`、直接 `torch.tensor(...)`。

**【你的预测】**

（写出三个函数调用）

*ps.书上好像没有torch.full（）*

In [7]:
help(torch.full)

Help on built-in function full in module torch:

full(...)
    full(size, fill_value, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) -> Tensor
    
    Creates a tensor of size :attr:`size` filled with :attr:`fill_value`. The
    tensor's dtype is inferred from :attr:`fill_value`.
    
    Args:
        size (int...): a list, tuple, or :class:`torch.Size` of integers defining the
            shape of the output tensor.
        fill_value (Scalar): the value to fill the output tensor with.
    
    Keyword args:
        out (Tensor, optional): the output tensor.
        dtype (:class:`torch.dtype`, optional): the desired data type of returned tensor.
            Default: if ``None``, uses a global default (see :func:`torch.set_default_dtype`).
        layout (:class:`torch.layout`, optional): the desired layout of returned Tensor.
            Default: ``torch.strided``.
        device (:class:`torch.device`, optional): the desired device of returned ten

In [9]:
# 方法一
torch.ones(3,2)
# 方法二
torch.full((3,2),1)
# 方法三
torch.tensor([[1,1],
              [1,1],
              [1,1]])

tensor([[1, 1],
        [1, 1],
        [1, 1]])

## 题 3 🌱 `rand` 与 `randn` 的分布差异

各采样 1000 个数，观察它们的**取值范围**。运行后回答：为什么 `rand` 的值都在 [0, 1) 内，而 `randn` 会有负数？

In [10]:
a = torch.rand(1000)
b = torch.randn(1000)
print('rand  : min =', a.min().item(), ' max =', a.max().item(), ' mean =', a.mean().item())
print('randn : min =', b.min().item(), ' max =', b.max().item(), ' mean =', b.mean().item())

rand  : min = 0.00033283233642578125  max = 0.9999308586120605  mean = 0.5096927881240845
randn : min = -3.559007167816162  max = 3.13991379737854  mean = -0.03650425747036934


In [12]:
help(torch.randn)

Help on built-in function randn in module torch:

randn(...)
    randn(*size, *, generator=None, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False, pin_memory=False) -> Tensor
    
    
    Returns a tensor filled with random numbers from a normal distribution
    with mean `0` and variance `1` (also called the standard normal
    distribution).
    
    .. math::
        \text{out}_{i} \sim \mathcal{N}(0, 1)
    
    For complex dtypes, the tensor is i.i.d. sampled from a `complex normal distribution`_ with zero mean and
    unit variance as
    
    .. math::
        \text{out}_{i} \sim \mathcal{CN}(0, 1)
    
    This is equivalent to separately sampling the real :math:`(\operatorname{Re})` and imaginary
    :math:`(\operatorname{Im})` part of :math:`\text{out}_i` as
    
    .. math::
        \operatorname{Re}(\text{out}_{i}) \sim \mathcal{N}(0, \frac{1}{2}),\quad
        \operatorname{Im}(\text{out}_{i}) \sim \mathcal{N}(0, \frac{1}{2})
    
    The shap

**【你的观察结论】**
torch.rand非负且位于某一特定区间内
（Returns a tensor filled with random numbers from a uniform distribution
    on the interval :math:`[0, 1)`）
torch.randn就没有这样的特征
（Returns a tensor filled with random numbers from a normal distribution
with mean `0` and variance `1` (also called the standard normal distribution).）

## 题 4 🌱 二维 `cat` 形状预测

`A`、`B` 都是 `(2, 3)`。预测 `dim=0` 和 `dim=1` 拼接后的形状与内容。

**【你的预测】**

- `dim=0` → 形状 （4，3），内容：2行+2行叠起来
- `dim=1` → 形状 （2，6），内容：3列+3列叠起来

In [13]:
A = torch.tensor([[1., 2., 3.], [4., 5., 6.]])
B = torch.tensor([[7., 8., 9.], [10., 11., 12.]])
print(torch.cat((A, B), dim=0), '\n')
print(torch.cat((A, B), dim=1))

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]]) 

tensor([[ 1.,  2.,  3.,  7.,  8.,  9.],
        [ 4.,  5.,  6., 10., 11., 12.]])


## 题 5 🔧 三维 `cat` 形状预测

`A`、`B` 都是 `(2, 3, 4)`。预测三个维度各自拼接后的形状。

**【你的预测】**

- `dim=0` → (4, 3, 4)
- `dim=1` → (2, 6, 4)
- `dim=2` → (2, 3, 8)

In [14]:
A = torch.ones(2, 3, 4)
B = torch.zeros(2, 3, 4)
print('dim=0:', torch.cat((A, B), dim=0).shape)
print('dim=1:', torch.cat((A, B), dim=1).shape)
print('dim=2:', torch.cat((A, B), dim=2).shape)

dim=0: torch.Size([4, 3, 4])
dim=1: torch.Size([2, 6, 4])
dim=2: torch.Size([2, 3, 8])


## 题 6 🌱 索引预测（已判定完成，但是由于输入问题就此从略）

`X` 是 `(3, 4)`。预测下面每个表达式的**值**和**形状**：

| 表达式 | 值 | 形状 |
|---|---|---|
| `X[-1]` | | |
| `X[1:3]` | | |
| `X[1, 2]` | | |
| `X[1][2]` | | |
| `X[1:3, 1:3]` | | |

In [3]:
X = torch.arange(12).reshape(3, 4)
print('X =\n', X, '\n')
print('X[-1] =\n', X[-1], '\n')
print('X[1:3] =\n', X[1:3], '\n')
print('X[1, 2] =', X[1, 2], '\n')
print('X[1][2] =', X[1][2], '\n')
print('X[1:3, 1:3] =\n', X[1:3, 1:3])

X =
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]) 

X[-1] =
 tensor([ 8,  9, 10, 11]) 

X[1:3] =
 tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]) 

X[1, 2] = tensor(6) 

X[1][2] = tensor(6) 

X[1:3, 1:3] =
 tensor([[ 5,  6],
        [ 9, 10]])


## 题 7 🔧 `reshape` 的花式玩法与 `-1` 的含义

把 12 个元素 reshape 成各种形状，逐一运行。观察 `-1` 起了什么作用？

**【你的预测】**`X.reshape(-1, 4)` 会得到形状 （3，4）

In [4]:
X = torch.arange(12)
print(X.reshape(2, 6).shape)   # → ?
print(X.reshape(4, 3).shape)   # → ?
print(X.reshape(6, 2).shape)   # → ?
print(X.reshape(12).shape)     # → ?
print(X.reshape(-1, 4).shape)  # → ?  -1 是什么意思？
print(X.reshape(3, -1).shape)  # → ?

torch.Size([2, 6])
torch.Size([4, 3])
torch.Size([6, 2])
torch.Size([12])
torch.Size([3, 4])
torch.Size([3, 4])


**conclusion**：感觉像是自动补全参数的意思

## 题 8 🔧 原地操作 vs 非原地操作

运行后回答：`Y = X + 2` 之后 `X` 变了吗？`X += 2` 之后呢？再试试 `X.add_(2)`（带下划线 `_`）。

**【你的预测】**

- `Y = X + 2` 后 X：不变
- `X += 2` 后 X：变

In [6]:
X = torch.zeros(2, 3)
print('初始 X =', X)
Y = X + 2
print('Y = X + 2 之后，X =', X)   # X 变了没？
X += 2                             # 等价于 X.add_(2)，原地操作
print('X += 2 之后，X =', X)       # 这次呢？
X -= 2
X.add_(2)
print('X.add_(2) = ',X)

初始 X = tensor([[0., 0., 0.],
        [0., 0., 0.]])
Y = X + 2 之后，X = tensor([[0., 0., 0.],
        [0., 0., 0.]])
X += 2 之后，X = tensor([[2., 2., 2.],
        [2., 2., 2.]])
X.add_(2) =  tensor([[2., 2., 2.],
        [2., 2., 2.]])


## 题 9 🚀 挑战：模拟一个图像 batch

深度学习里图像通常表示为 `(batch, channel, height, width)`。

1. 创建 `(2, 3, 4, 4)` 的张量：2 张 RGB 彩色图，每张 4×4 像素；
2. 取出**第 1 张图的 R 通道**（提示：两层索引）；
3. 用 `permute` 把通道放到最后，变成 `(2, 4, 4, 3)` 的 HWC 格式（OpenCV/TensorFlow 习惯）。

**【你的预测】**第 2 步取出的形状是 ____，第 3 步 permute 的参数是 ____

In [11]:
help(torch.permute)

Help on built-in function permute in module torch:

permute(...)
    permute(input, dims) -> Tensor
    
    Returns a view of the original tensor :attr:`input` with its dimensions permuted.
    
    Args:
        input (Tensor): the input tensor.
        dims (tuple of int): The desired ordering of dimensions
    
    Example:
        >>> x = torch.randn(2, 3, 5)
        >>> x.size()
        torch.Size([2, 3, 5])
        >>> torch.permute(x, (2, 0, 1)).size()
        torch.Size([5, 2, 3])



In [15]:
# 1. 创建图像 batch，用 arange 填充以便区分像素
imgs = torch.arange(2 * 3 * 4 * 4).reshape(2, 3, 4, 4)
print('imgs.shape =', imgs.shape)

# 2. 取出第 1 张图的 R 通道（写出你的代码）
R = imgs[0,0,:,:]
print('img.1R = ', R)
# 3. 转成 HWC 格式 (2, 4, 4, 3)（写出你的代码）
imgs = torch.permute(imgs,(0,2,3,1))
print('HWC:', imgs)

imgs.shape = torch.Size([2, 3, 4, 4])
img.1R =  tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])
HWC: tensor([[[[ 0, 16, 32],
          [ 1, 17, 33],
          [ 2, 18, 34],
          [ 3, 19, 35]],

         [[ 4, 20, 36],
          [ 5, 21, 37],
          [ 6, 22, 38],
          [ 7, 23, 39]],

         [[ 8, 24, 40],
          [ 9, 25, 41],
          [10, 26, 42],
          [11, 27, 43]],

         [[12, 28, 44],
          [13, 29, 45],
          [14, 30, 46],
          [15, 31, 47]]],


        [[[48, 64, 80],
          [49, 65, 81],
          [50, 66, 82],
          [51, 67, 83]],

         [[52, 68, 84],
          [53, 69, 85],
          [54, 70, 86],
          [55, 71, 87]],

         [[56, 72, 88],
          [57, 73, 89],
          [58, 74, 90],
          [59, 75, 91]],

         [[60, 76, 92],
          [61, 77, 93],
          [62, 78, 94],
          [63, 79, 95]]]])


## 题 10 🚀 挑战：闭卷综合默写

**不看教材**，从空 cell 开始，依次完成：

1. 创建 `arange(12)` 并 reshape 成 `(3, 4)`
2. 转置它（`.T`），观察形状变化
3. 把原矩阵和它自己沿 `dim=1` 拼接
4. 对整个结果求和（得到一个标量）
5. 转成 numpy 数组，打印其类型

全部写出来后，对照教材 2.1 检查自己的写法。

In [17]:
# 你的实现（写在这里）
a = torch.arange(12).reshape(3,4)
print("转置结果：", a.T)
processed = torch.cat((a,a), dim = 1)
b = torch.sum(processed)
b_numpy = b.numpy()
print(type(b_numpy))


转置结果： tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])
<class 'numpy.ndarray'>
