# ex04 · 线性代数（对应教材 2.3）

> 这节练的不是「会调 API」，而是**手算和代码对得上**——先手算，再运行验证。
> 答案在 `solutions/ex04-答案.md`。

In [1]:
import torch

## 题 1 🌱 转置

`A = torch.arange(9).reshape(3, 3)`。手写 A 和 A.T 的完整矩阵。

In [2]:
A = torch.arange(9).reshape(3, 3)
print('A =\n', A, '\n')
print('A.T =\n', A.T)

A =
 tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]) 

A.T =
 tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])


## 题 2 🌱 `torch.dot` 只接受一维向量

预测：对两个二维张量调用 `torch.dot` 会怎样？运行验证。

In [3]:
x = torch.tensor([1., 2., 3.])
y = torch.tensor([4., 5., 6.])
print('一维 dot =', torch.dot(x, y))     # 手算应等于 1*4+2*5+3*6 = 32

A2d = torch.ones(2, 3)
try:
    print(torch.dot(A2d, A2d))
except Exception as e:
    print('二维 dot 报错：', e)

一维 dot = tensor(32.)
二维 dot 报错： 1D tensors expected, but got 2D and 2D tensors


## 题 3 🌱 矩阵-向量积 `torch.mv`

手算 `torch.mv(A, v)` 的结果，其中 `A = [[1,2],[3,4]]`，`v = [1, 1]`。

In [4]:
A = torch.tensor([[1., 2.], [3., 4.]])
v = torch.tensor([1., 1.])
print('A =', A)
print('v =', v)
print('mv =', torch.mv(A, v))     # 手算：每行与 v 点积
print('A @ v 也行 =', A @ v)

A = tensor([[1., 2.],
        [3., 4.]])
v = tensor([1., 1.])
mv = tensor([3., 7.])
A @ v 也行 = tensor([3., 7.])


## 题 4 🌱 矩阵-矩阵积 `torch.mm`

手算 `A @ B`，其中 `A = [[1,2],[3,4]]`（2×2），`B = [[1,0],[0,1]]`（单位阵）。

**思考**：乘单位阵的结果是什么？这解释了「单位矩阵 = 矩阵世界里的 1」。

In [5]:
A = torch.tensor([[1., 2.], [3., 4.]])
I = torch.eye(2)          # 2×2 单位阵
print('A =\n', A, '\n')
print('I =\n', I, '\n')
print('A @ I =\n', A @ I)

A =
 tensor([[1., 2.],
        [3., 4.]]) 

I =
 tensor([[1., 0.],
        [0., 1.]]) 

A @ I =
 tensor([[1., 2.],
        [3., 4.]])


## 题 5 🔧 容易混淆：`*`（逐元素/广播）vs `@`（矩阵乘）

`A` 是 `(3, 3)`，`b` 是 `(3, 1)`。预测：

- `A * b` 合法吗？结果形状 (3, 3)（提示：广播！）
- `A @ b` 合法吗？结果形状 (3, 1)

In [6]:
A = torch.arange(9, dtype=torch.float32).reshape(3, 3)
b = torch.ones(3, 1)
print('A * b =\n', A * b, ' 形状', (A * b).shape, '\n')   # 逐元素 + 广播
print('A @ b =\n', A @ b, ' 形状', (A @ b).shape)          # 矩阵乘

A * b =
 tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])  形状 torch.Size([3, 3]) 

A @ b =
 tensor([[ 3.],
        [12.],
        [21.]])  形状 torch.Size([3, 1])


ps: a@b是万能乘法，可以自动选择torch.dot,torch.mv,torch.mm

## 题 6 🔧 降维求和

`A = torch.arange(9).reshape(3, 3)`。先手算，再验证：

| 表达式 | 手算结果 |
|---|---|
| `A.sum(axis=0)` | 每列之和 = [9, 12, 15] |
| `A.sum(axis=1)` | 每行之和 = [3, 12, 21]|
| `A.sum(axis=[0, 1])` | 总和 = [36]|

In [7]:
A = torch.arange(9).reshape(3, 3)
print('A =\n', A, '\n')
print('sum(axis=0) =', A.sum(axis=0))
print('sum(axis=1) =', A.sum(axis=1))
print('sum(axis=[0,1]) =', A.sum(axis=[0, 1]))

A =
 tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]) 

sum(axis=0) = tensor([ 9, 12, 15])
sum(axis=1) = tensor([ 3, 12, 21])
sum(axis=[0,1]) = tensor(36)


## 题 7 🌱 范数手算

1. `v = [3, 4]`：L2 范数 = 5（提示：勾股定理！）
2. `v = [1, -2, 3]`：L1 范数 = 6
3. `A = [[1,2],[3,4]]`：Frobenius 范数 = √30（提示：√(1+4+9+16)）

In [8]:
v1 = torch.tensor([3., 4.])
v2 = torch.tensor([1., -2., 3.])
A = torch.tensor([[1., 2.], [3., 4.]])

print('L2 范数 [3,4]  =', torch.norm(v1))          # 默认 L2
print('L1 范数 [1,-2,3] =', torch.abs(v2).sum())
print('Frobenius 范数 =', torch.norm(A))            # 对矩阵默认 Frobenius

L2 范数 [3,4]  = tensor(5.)
L1 范数 [1,-2,3] = tensor(6.)
Frobenius 范数 = tensor(5.4772)


## 题 8 🔧 `mean(axis=0)` vs `sum(axis=0)/numel()`

`A = torch.arange(6, dtype=torch.float32).reshape(2, 3)`。

预测：`A.mean(axis=0)` 和 `A.sum(axis=0) / A.numel()` 相等吗？为什么？运行验证。
不相等，一个是除以行数一个是除以所有元素的个数

In [9]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
print('A =\n', A, '\n')
print('mean(axis=0)      =', A.mean(axis=0))
print('sum(axis=0)/numel =', A.sum(axis=0) / A.numel())

A =
 tensor([[0., 1., 2.],
        [3., 4., 5.]]) 

mean(axis=0)      = tensor([1.5000, 2.5000, 3.5000])
sum(axis=0)/numel = tensor([0.5000, 0.8333, 1.1667])


## 题 9 🚀 挑战：特征向量直觉

对矩阵 `A = [[2, 0], [0, 3]]`（对角阵），向量 `[1, 0]` 和 `[0, 1]` 是特征向量吗？

1. 手算 `A @ [1, 0]` 和 `A @ [0, 1]`，观察方向是否改变 否， 否
2. 手算 `A @ [1, 1]`，方向变了吗？否
3. 用一句话总结：对角阵的特征向量指向哪里？

In [10]:
A = torch.tensor([[2., 0.], [0., 3.]])
e1 = torch.tensor([1., 0.])
e2 = torch.tensor([0., 1.])
v  = torch.tensor([1., 1.])
print('A @ [1,0] =', A @ e1)   # 方向变了吗？
print('A @ [0,1] =', A @ e2)
print('A @ [1,1] =', A @ v)

A @ [1,0] = tensor([2., 0.])
A @ [0,1] = tensor([0., 3.])
A @ [1,1] = tensor([2., 3.])


特征值就是对角线上的数。这解释了为什么"特征向量 = 不被矩阵改变方向的向量"（只被拉伸/压缩）。